<?php return array (
    'AF' => ['currency' => 'Afghan Afghani', 'iso' => 'AFN'],
    'AX' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'AL' => ['currency' => 'Albanian Lek', 'iso' => 'ALL'],
    'DZ' => ['currency' => 'Algerian Dinar', 'iso' => 'DZD'],
    'AS' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'AD' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'AO' => ['currency' => 'Angolan Kwanza', 'iso' => 'AOA'],
    'AI' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'AQ' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'AG' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'AR' => ['currency' => 'Argentina Peso', 'iso' => 'ARS'],
    'AM' => ['currency' => 'Armenian Drams', 'iso' => 'AMD'],
    'AW' => ['currency' => 'Aruba Guilder', 'iso' => 'AWG'],
    'AC' => ['currency' => 'Saint Helena Pound', 'iso' => 'SHP'],
    'AU' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'AT' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'AZ' => ['currency' => 'Azerbaijani Manat', 'iso' => 'AZN'],
    'BS' => ['currency' => 'Bahamas Dollar', 'iso' => 'BSD'],
    'BH' => ['currency' => 'Bahraini dinar', 'iso' => 'BHD'],
    'BD' => ['currency' => 'Bangladeshi Taka', 'iso' => 'BDT'],
    'BB' => ['currency' => 'Barbados Dollar', 'iso' => 'BBD'],
    'BY' => ['currency' => 'Belarusian Ruble', 'iso' => 'BYR'],
    'BE' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'BZ' => ['currency' => 'Belize Dollar', 'iso' => 'BZD'],
    'BJ' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'BM' => ['currency' => 'Bermuda Dollar', 'iso' => 'BMD'],
    'BT' => ['currency' => 'Bhutanese Ngultrum', 'iso' => 'BTN'],
    'BO' => ['currency' => 'Boliviano', 'iso' => 'BOB'],
    'BA' => ['currency' => 'Bosnia & Herzegovina Convertible Mark', 'iso' => 'BAM'],
    'BW' => ['currency' => 'Botswana Pula', 'iso' => 'BWP'],
    'BR' => ['currency' => 'Brazilian Real', 'iso' => 'BRL'],
    'IO' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'VG' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'BN' => ['currency' => 'Brunei Dollar', 'iso' => 'BND'],
    'BG' => ['currency' => 'Bulgarian Lev', 'iso' => 'BGN'],
    'BF' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'BI' => ['currency' => 'Burundian Franc', 'iso' => 'BIF'],
    'KH' => ['currency' => 'Cambodian Riel', 'iso' => 'KHR'],
    'CM' => ['currency' => 'Central African CFA Franc', 'iso' => 'XAF'],
    'CA' => ['currency' => 'Canadian Dollar', 'iso' => 'CAD'],
    'IC' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'CV' => ['currency' => 'Cape Verde Escudo', 'iso' => 'CVE'],
    'BQ' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'KY' => ['currency' => 'Cayman Islands Dollar', 'iso' => 'KYD'],
    'CF' => ['currency' => 'Central African CFA Franc', 'iso' => 'XAF'],
    'EA' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'TD' => ['currency' => 'Central African CFA Franc', 'iso' => 'XAF'],
    'CL' => ['currency' => 'Chile Peso', 'iso' => 'CLP'],
    'CN' => ['currency' => 'China Yuan Renminbi', 'iso' => 'CNY'],
    'CX' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'CC' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'CO' => ['currency' => 'Colombian Peso', 'iso' => 'COP'],
    'KM' => ['currency' => 'Comorian Franc', 'iso' => 'KMF'],
    'CG' => ['currency' => 'Central African CFA Franc', 'iso' => 'XAF'],
    'CD' => ['currency' => 'Congolese Franc', 'iso' => 'CDF'],
    'CK' => ['currency' => 'New Zealand Dollar', 'iso' => 'NZD'],
    'CR' => ['currency' => 'Costa Rican Colon', 'iso' => 'CRC'],
    'CI' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'HR' => ['currency' => 'Croatian Kuna', 'iso' => 'HRK'],
    'CU' => ['currency' => 'Cuban Peso', 'iso' => 'CUP'],
    'CW' => ['currency' => 'Netherlands Antillean Guilder', 'iso' => 'ANG'],
    'CY' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'CZ' => ['currency' => 'Czech Koruna', 'iso' => 'CZK'],
    'DK' => ['currency' => 'Denmark Krone', 'iso' => 'DKK'],
    'DG' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'DJ' => ['currency' => 'Djiboutian Franc', 'iso' => 'DJF'],
    'DM' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'DO' => ['currency' => 'Dominican Peso', 'iso' => 'DOP'],
    'EC' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'EG' => ['currency' => 'Egyptian Pound', 'iso' => 'EGP'],
    'SV' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'GQ' => ['currency' => 'Central African CFA Franc', 'iso' => 'XAF'],
    'ER' => ['currency' => 'Eritrean Nakfa', 'iso' => 'ERN'],
    'EE' => ['currency' => 'Estonia Kroon', 'iso' => 'EEK'],
    'ET' => ['currency' => 'Ethiopian Birr', 'iso' => 'ETB'],
    'EZ' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'FK' => ['currency' => 'Falkland Islands Pound', 'iso' => 'FKP'],
    'FO' => ['currency' => 'Danish Krone', 'iso' => 'DKK'],
    'FJ' => ['currency' => 'Fijian Dollar', 'iso' => 'FJD'],
    'FI' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'FR' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'GF' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'PF' => ['currency' => 'CFP Franc', 'iso' => 'XPF'],
    'TF' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'GA' => ['currency' => 'CFP Franc', 'iso' => 'XPF'],
    'GM' => ['currency' => 'Gambian Dalasi', 'iso' => 'GMD'],
    'GE' => ['currency' => 'Georgian Lari', 'iso' => 'GEL'],
    'DE' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'GH' => ['currency' => 'Ghanaian Cedi', 'iso' => 'GHS'],
    'GI' => ['currency' => 'Gibraltar Pound', 'iso' => 'GIP'],
    'GR' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'GL' => ['currency' => 'Danish Krone', 'iso' => 'DKK'],
    'GD' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'GP' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'GU' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'GT' => ['currency' => 'Guatemalan Quetzal', 'iso' => 'GTQ'],
    'GG' => ['currency' => 'Guernsey Pound', 'iso' => 'GGP'],
    'GN' => ['currency' => 'Guinea Franc', 'iso' => 'GNF'],
    'GW' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'GY' => ['currency' => 'Guyanese Dollar', 'iso' => 'GYD'],
    'HT' => ['currency' => 'Haitian Gourde', 'iso' => 'HTG'],
    'HN' => ['currency' => 'Honduran Lempira', 'iso' => 'HNL'],
    'HK' => ['currency' => 'Hong Kong Dollar', 'iso' => 'HKD'],
    'HU' => ['currency' => 'Hungarian Forint', 'iso' => 'HUF'],
    'IS' => ['currency' => 'Icelandic Króna', 'iso' => 'ISK'],
    'IN' => ['currency' => 'Indian Rupee', 'iso' => 'INR'],
    'ID' => ['currency' => 'Indonesian Rupiah', 'iso' => 'IDR'],
    'IR' => ['currency' => 'Iranian Rial', 'iso' => 'IRR'],
    'IQ' => ['currency' => 'Iraqi Dinar', 'iso' => 'IQD'],
    'IE' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'IM' => ['currency' => 'Pound Sterling', 'iso' => 'GBP'],
    'IL' => ['currency' => 'Israeli New Shekel', 'iso' => 'ILS'],
    'IT' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'JM' => ['currency' => 'Jamaican Dollar', 'iso' => 'JMD'],
    'JP' => ['currency' => 'Japanese Yen', 'iso' => 'JPY'],
    'JE' => ['currency' => 'Jersey Pound', 'iso' => 'JEP'],
    'JO' => ['currency' => 'Jordanian Dinar', 'iso' => 'JOD'],
    'KZ' => ['currency' => 'Kazakhstani Tenge', 'iso' => 'KZT'],
    'KE' => ['currency' => 'Kenyan Shilling', 'iso' => 'KES'],
    'KI' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'XK' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'KW' => ['currency' => 'Kuwaiti Dinar', 'iso' => 'KWD'],
    'KG' => ['currency' => 'Kyrgyzstani Som', 'iso' => 'KGS'],
    'LA' => ['currency' => 'Lao Kip', 'iso' => 'LAK'],
    'LV' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'LB' => ['currency' => 'Lebanese Pound', 'iso' => 'LBP'],
    'LS' => ['currency' => 'Lesotho Loti', 'iso' => 'LSL'],
    'LR' => ['currency' => 'Liberian Dollar', 'iso' => 'LRD'],
    'LY' => ['currency' => 'Libyan Dinar', 'iso' => 'LYD'],
    'LI' => ['currency' => 'Swiss Franc', 'iso' => 'CHF'],
    'LT' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'LU' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'MO' => ['currency' => 'Macanese Pataca', 'iso' => 'MOP'],
    'MK' => ['currency' => 'Macedonian Denar', 'iso' => 'MKD'],
    'MG' => ['currency' => 'Malagasy Ariary', 'iso' => 'MGA'],
    'MW' => ['currency' => 'Malawian Kwacha', 'iso' => 'MWK'],
    'MY' => ['currency' => 'Malaysian Ringgit', 'iso' => 'MYR'],
    'MV' => ['currency' => 'Maldivian Rufiyaa', 'iso' => 'MVR'],
    'ML' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'MT' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'MH' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'MQ' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'MR' => ['currency' => 'Mauritanian Ouguiya', 'iso' => 'MRO'],
    'MU' => ['currency' => 'Mauritian Rupee', 'iso' => 'MUR'],
    'YT' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'MX' => ['currency' => 'Mexican Peso', 'iso' => 'MXN'],
    'FM' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'MD' => ['currency' => 'Moldovan Leu', 'iso' => 'MDL'],
    'MC' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'MN' => ['currency' => 'Mongolian Tögrög', 'iso' => 'MNT'],
    'ME' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'MS' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'MA' => ['currency' => 'Moroccan Dirham', 'iso' => 'MAD'],
    'MZ' => ['currency' => 'Mozambican Metical', 'iso' => 'MZN'],
    'MM' => ['currency' => 'Myanmar Kyat', 'iso' => 'MMK'],
    'NA' => ['currency' => 'South Africa Rand', 'iso' => 'ZAR'],
    'NR' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'NP' => ['currency' => 'Nepalese Rupee', 'iso' => 'NPR'],
    'NL' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'NC' => ['currency' => 'CFP Franc', 'iso' => 'XPF'],
    'NZ' => ['currency' => 'New Zealand Dollar', 'iso' => 'NZD'],
    'NI' => ['currency' => 'Nicaraguan Córdoba', 'iso' => 'NIO'],
    'NE' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'NG' => ['currency' => 'Nigerian Naira', 'iso' => 'NGN'],
    'NU' => ['currency' => 'New Zealand Dollar', 'iso' => 'NZD'],
    'NF' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'KP' => ['currency' => 'North Korean Won', 'iso' => 'KPW'],
    'MP' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'NO' => ['currency' => 'Norwegian Krone', 'iso' => 'NOK'],
    'OM' => ['currency' => 'Omani Rial', 'iso' => 'OMR'],
    'PK' => ['currency' => 'Pakistani Rupee', 'iso' => 'PKR'],
    'PW' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'PS' => ['currency' => 'No Currency', 'iso' => 'XXX'],
    'PA' => ['currency' => 'Panamanian Balboa', 'iso' => 'PAB'],
    'PG' => ['currency' => 'Papua New Guinean Kina', 'iso' => 'PGK'],
    'PY' => ['currency' => 'Paraguayan Guaraní', 'iso' => 'PYG'],
    'PE' => ['currency' => 'Peru Nuevo Sol', 'iso' => 'PEN'],
    'PH' => ['currency' => 'Philippines Peso', 'iso' => 'PHP'],
    'PN' => ['currency' => 'New Zealand Dollar', 'iso' => 'NZD'],
    'PL' => ['currency' => 'Polish Złoty', 'iso' => 'PLN'],
    'PT' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'PR' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'QA' => ['currency' => 'Qatari Riyal', 'iso' => 'QAR'],
    'RE' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'RO' => ['currency' => 'Romanian Leu', 'iso' => 'ROL'],
    'RU' => ['currency' => 'Russian Ruble', 'iso' => 'RUB'],
    'RW' => ['currency' => 'Rwandan Franc', 'iso' => 'RWF'],
    'WS' => ['currency' => 'Samoan Tālā', 'iso' => 'WST'],
    'SM' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'ST' => ['currency' => 'São Tomé & Príncipe Dobra', 'iso' => 'STD'],
    'SA' => ['currency' => 'Saudi Riyal', 'iso' => 'SAR'],
    'SN' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'RS' => ['currency' => 'Serbian Dinar', 'iso' => 'RSD'],
    'SC' => ['currency' => 'Seychellois Rupee', 'iso' => 'SCR'],
    'SL' => ['currency' => 'Sierra Leonean Leone', 'iso' => 'SLL'],
    'SG' => ['currency' => 'Singapore Dollar', 'iso' => 'SGD'],
    'SX' => ['currency' => 'Netherlands Antillean Guilder', 'iso' => 'ANG'],
    'SK' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'SI' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'SB' => ['currency' => 'Solomon Islands Dollar', 'iso' => 'SBD'],
    'SO' => ['currency' => 'Somalia Shilling', 'iso' => 'SOS'],
    'ZA' => ['currency' => 'South African Rand', 'iso' => 'ZAR'],
    'GS' => ['currency' => 'Falkland Islands Pound', 'iso' => 'FKP'],
    'KR' => ['currency' => 'South Korean Won', 'iso' => 'KRW'],
    'SS' => ['currency' => 'South Sudanese Pound', 'iso' => 'SSP'],
    'ES' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'LK' => ['currency' => 'Sri Lankan Rupee', 'iso' => 'LKR'],
    'BL' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'SH' => ['currency' => 'St. Helena Pound', 'iso' => 'SHP'],
    'KN' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'LC' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'MF' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'PM' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'VC' => ['currency' => 'Eastern Caribbean Dollar', 'iso' => 'XCD'],
    'SD' => ['currency' => 'Sudanese Pound', 'iso' => 'SDG'],
    'SR' => ['currency' => 'Surinamese Dollar', 'iso' => 'SRD'],
    'SJ' => ['currency' => 'Norwegian Krone', 'iso' => 'NOK'],
    'SZ' => ['currency' => 'South African Rand', 'iso' => 'ZAR'],
    'SE' => ['currency' => 'Swedish Krona', 'iso' => 'SEK'],
    'CH' => ['currency' => 'Swiss Franc', 'iso' => 'CHF'],
    'SY' => ['currency' => 'Syrian Pound', 'iso' => 'SYP'],
    'TW' => ['currency' => 'Taiwan New Dollar', 'iso' => 'TWD'],
    'TJ' => ['currency' => 'Tajikistani Somoni', 'iso' => 'TJS'],
    'TZ' => ['currency' => 'Tanzanian Shilling', 'iso' => 'TZS'],
    'TH' => ['currency' => 'Thai Baht', 'iso' => 'THB'],
    'TL' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'TG' => ['currency' => 'West African CFA Franc', 'iso' => 'XOF'],
    'TK' => ['currency' => 'New Zealand Dollar', 'iso' => 'NZD'],
    'TO' => ['currency' => 'Tongan paʻanga', 'iso' => 'TOP'],
    'TT' => ['currency' => 'Trinidad & Tobago Dollar', 'iso' => 'TTD'],
    'TA' => ['currency' => 'Pound Sterling', 'iso' => 'GBP'],
    'TN' => ['currency' => 'Tunisian Dinar', 'iso' => 'TND'],
    'TR' => ['currency' => 'Turkish Lira', 'iso' => 'TRY'],
    'TM' => ['currency' => 'Turkmenistani Manat', 'iso' => 'TMT'],
    'TC' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'TV' => ['currency' => 'Australian Dollar', 'iso' => 'AUD'],
    'UM' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'VI' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'UG' => ['currency' => 'Ugandan Shilling', 'iso' => 'UGX'],
    'UA' => ['currency' => 'Ukrainian Hryvnia', 'iso' => 'UAH'],
    'AE' => ['currency' => 'United Arab Emirates Dirham', 'iso' => 'AED'],
    'GB' => ['currency' => 'Pound Sterling', 'iso' => 'GBP'],
    'UN' => ['currency' => 'No Currency', 'iso' => 'XXX'],
    'US' => ['currency' => 'United States Dollar', 'iso' => 'USD'],
    'UY' => ['currency' => 'Uruguayan Peso', 'iso' => 'UYU'],
    'UZ' => ['currency' => 'Uzbekistan Som', 'iso' => 'UZS'],
    'VU' => ['currency' => 'Vanuatu Vatu', 'iso' => 'VUV'],
    'VA' => ['currency' => '‎Euro', 'iso' => 'EUR'],
    'VE' => ['currency' => 'Venezuelan bolívar', 'iso' => 'VEF'],
    'VN' => ['currency' => 'Vietnamese Dồng', 'iso' => 'VND'],
    'WF' => ['currency' => 'CFP Franc', 'iso' => 'XPF'],
    'EH' => ['currency' => 'Sahrawi Peseta', 'iso' => 'EHP'],
    'YE' => ['currency' => 'Yemeni Riyal', 'iso' => 'YER'],
    'ZM' => ['currency' => 'Zambian Kwacha', 'iso' => 'ZMW'],
    'ZW' => ['currency' => 'Zimbabwean Dollar', 'iso' => 'ZWL'],
);
